name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

  workflow_dispatch:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: gokart version
