name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

  workflow_dispatch:

jobs:
  trunk-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
